name: KACGI
channels:
  - defaults
  - pytorch
  - https://download.pytorch.org/whl/torch_stable.html
dependencies:
  - python=3.7
  - pip
  - pip:
      - numpy
      - pandas
      - scipy
      - scikit-learn
      - torch==1.8.0+cu111
      - torchvision==0.9.0+cu111
      - torchaudio==0.8.0
